spring:
  datasource:
    url: jdbc:mysql://comstering.synology.me:3306/lomeone-dev
    username: lomeone-dev
    password: xwB388$#t^%A~$k
    hikari:
      maximum-pool-size: 4
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: mms-images-data

jwt:
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

logging:
  level:
    root: DEBUG
