container:
  activeProfile: "production"
  replicas: 1

image:
  tag: main

service:
  internal: true
  annotations: {}

ingress:
  domain: server.lomeone.com
  annotations: {}

resources:
  limits:
    cpu: 1.0
    memory: 1024Mi

  requests:
    cpu: 0.1
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
