container:
  activeProfile: "staging"
  replicas: 1

image:
  tag: staging

service:
  internal: true
  annotations: {}

ingress:
  domain: staging-server.lomeone.com
  annotations: {}

resources:
  limits:
    cpu: 0.5
    memory: 1024Mi

  requests:
    cpu: 0.1
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
